import { Permission } from "../types/auth-types";
import { UserRole } from "../interfaces/user-interface";

export const ROLE_PERMISSIONS: Record<UserRole, Permission[]> = {
  [UserRole.SUPER_ADMIN]: [
    "createMeeting",
    "updateMeeting",
    "deleteMeeting",
    "getMeeting",
    "startMeeting",
    "endMeeting",
    "joinMeeting",
    "startRecording",
    "stopRecording",
    "viewRecording",
    "deleteRecording",
    "downloadRecording",
    "manageApiKeys",
    "manageMembers",
    "manageBilling",
    "manageUsers",
    "assignRoles",
    "suspendUsers",
  ],
  [UserRole.ADMIN]: [
    "createMeeting",
    "updateMeeting",
    "deleteMeeting",
    "getMeeting",
    "startMeeting",
    "endMeeting",
    "joinMeeting",
    "startRecording",
    "stopRecording",
    "viewRecording",
    "deleteRecording",
    "downloadRecording",
    "manageMembers",
    "manageBilling",
    "manageUsers",
    "assignRoles",
  ],
  [UserRole.MENTOR]: [
    "createMeeting",
    "updateMeeting",
    "startMeeting",
    "endMeeting",
    "getMeeting",
    "joinMeeting",
    "startRecording",
    "stopRecording",
    "viewRecording",
    "downloadRecording",
  ],
  [UserRole.STUDENT]: [
    "joinMeeting",
  ],
  [UserRole.BLOCKED]: [],
  [UserRole.DELETED]: [],
  [UserRole.SERVICE_ACCOUNT]: [],
};
