import { Permission } from "../types/auth.types";
import { ParticipantRole, UserRole } from "@/types/roles";

export const USER_ROLE_PERMISSIONS: Record<UserRole, Permission[]> = {
  [UserRole.SUPER_ADMIN]: [
    "createMeeting",
    "updateMeeting",
    "deleteMeeting",
    "getMeeting",
    "startMeeting",
    "endMeeting",
    "createParticipantJoinUrl",
    "getParticipantJoinUrl",
    "deleteParticipantJoinUrl",
    "startRecording",
    "stopRecording",
    "viewRecording",
    "deleteRecording",
    "downloadRecording",
    "manageApiKeys",
    "manageMembers",
    "manageBilling",
    "manageUsers",
    "assignRoles",
    "suspendUsers",
  ],
  [UserRole.ADMIN]: [
    "createMeeting",
    "updateMeeting",
    "deleteMeeting",
    "getMeeting",
    "startMeeting",
    "endMeeting",
    "createParticipantJoinUrl",
    "getParticipantJoinUrl",
    "deleteParticipantJoinUrl",
    "startRecording",
    "stopRecording",
    "viewRecording",
    "deleteRecording",
    "downloadRecording",
    "createApiKey",
  ],
  [UserRole.BLOCKED]: [],
  [UserRole.DELETED]: [],
  [UserRole.SERVICE_ACCOUNT]: [],
};

export const MEETING_ROLE_PERMISSIONS: Record<ParticipantRole, Permission[]> = {
  [ParticipantRole.HOST]: [
    "createMeeting",
    "updateMeeting",
    "deleteMeeting",
    "getMeeting",
    "startMeeting",
    "endMeeting",
    "startRecording",
    "stopRecording",
    "viewRecording",
    "deleteRecording",
    "downloadRecording",
  ],
  [ParticipantRole.CO_HOST]: [
    "createMeeting",
    "updateMeeting",
    "deleteMeeting",
    "getMeeting",
    "startMeeting",
    "endMeeting",
    "startRecording",
    "stopRecording",
    "viewRecording",
    "deleteRecording",
    "downloadRecording",
  ],
  [ParticipantRole.PARTICIPANT]: [
    "createMeeting",
    "updateMeeting",
    "deleteMeeting",
    "getMeeting",
    "startMeeting",
    "endMeeting",
    "startRecording",
    "stopRecording",
    "viewRecording",
    "deleteRecording",
    "downloadRecording",
  ],
};